// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace Day2.Models;

[Table("Student")]
public partial class Student
{
    [Key]
    public int ID { get; set; }

    [StringLength(50)]
    public string name { get; set; }

    public int? age { get; set; }

    public string adddress { get; set; }

    public int? deptid { get; set; }

    [ForeignKey("deptid")]
    [InverseProperty("Students")]
    public virtual Department dept { get; set; }
}